name: Ember Test Audit comparison
description: Compare runs of Ember Test Audit
author: Buck Doyle
branding:
  icon: clock
  color: green
inputs:
  base-report-path:
    description: Path to the audit report for the comparison base
    required: true
  comparison-report-path:
    description: Path to the audit report to compare against the base
    required: true
  base-identifier:
    description: A title to identify what’s being compared against, perhaps a branch name
    default: Base
  comparison-identifier:
    description: A title to identify what’s being compared, perhaps a SHA
    default: Comparison
  timing-output-path:
    description: Path to write the timing comparison to
    required: true
  flakiness-output-path:
    description: Path to write the flakiness report
    required: true
runs:
  using: 'node12'
  main: 'index.js'
